### ISSUE TITLE
Error with `race` and sync Observables

### ISSUE THREAD

**Issue by nmote** [ReactiveX/rxjs#1615]
**RxJS version:**

5.0.0-beta.6

**Code to reproduce:**

At the Node (v5.0.0) console:

```
rx.Observable.race(rx.Observable.of(true), rx.Observable.of(false).delay(1500)).subscribe(console.log.bind(console))
```

**Expected behavior:**

```
true
```

**Actual behavior:**

```
true
TypeError: Cannot read property 'push' of null
    at RaceSubscriber._complete (/.../node_modules/@reactivex/rxjs/dist/cjs/operator/race.js:86:35)
    at RaceSubscriber.Subscriber.complete (/.../node_modules/@reactivex/rxjs/dist/cjs/Subscriber.js:113:18)
    at ArrayObservable._subscribe (/.../node_modules/@reactivex/rxjs/dist/cjs/observable/ArrayObservable.js:116:24)
    at ArrayObservable.Observable.subscribe (/.../node_modules/@reactivex/rxjs/dist/cjs/Observable.js:52:62)
    at Observable._subscribe (/.../node_modules/@reactivex/rxjs/dist/cjs/Observable.js:109:28)
    at RaceOperator.call (/.../node_modules/@reactivex/rxjs/dist/cjs/operator/race.js:55:23)
    at Observable.subscribe (/.../node_modules/@reactivex/rxjs/dist/cjs/Observable.js:52:38)
    at repl:1:81
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
```

**Additional information:**

If I `delay` both, I don't get the TypeError. If I use `toPromise` and then `.then` it, rather than calling `subscribe` I don't get the TypeError.

It seems clear that it's a result of one of the Observables being synchronous. However if this is expected behavior I have two questions: (1) What should I do instead, if I receive Observables that may or may not be sync? (2) Why does the error appear to be an internal error, rather than a user-facing error?

cc @matthewwithanm

**Comment by kwonoj** [comment]
I don't think this is expected behavior, Observable should not throw in this case. Let me try look into to see what's happening.

**Comment by blesh** [comment]
I was mildly excited when I thought @matthewwithanm was "Matthew with ham". Then I reread it. Can't win 'em all.
