### ISSUE TITLE
import RxJS in gulpfile.js will raise errors

### ISSUE THREAD

**Issue by xareelee** [ReactiveX/rxjs#1983]
I'm trying using RxJS in [gulp](http://gulpjs.com/) and following [this tutorial](https://markgoodyear.com/2015/06/using-es6-with-gulp/) to use ES6 in gulp. It works fine when I use ES6 syntax in the `gulpfile.js` with other libraries, but it raised errors when importing RxJS in the `gulpfile.js`. 
### First try

follow [the instructions](https://github.com/ReactiveX/rxjs#es6-via-npm)

``` js
import Rx from 'rxjs/Rx';
```

output when running `gulp default`:

```
$ gulp default

23:08:22] Requiring external module babel-register
module.js:442
    throw err;
    ^

Error: Cannot find module 'rxjs/Rx'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ({paths_to_project}/gulpfile.babel.js:8:1)
    at Module._compile (module.js:541:32)
    at loader ({paths_to_project}/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] ({paths_to_project}/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```
### Second try

change from `'rxjs/Rx'` to `rxjs-es/Rx`

``` js
import Rx from 'rxjs-es/Rx';
```

output when running `gulp default`:

```
$ gulp default

[23:21:02] Requiring external module babel-register
/Users/Xaree/Development/iOS/Playground/counter/node_modules/rxjs-es/Rx.js:5
export { Subject } from './Subject';
^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] ({paths_to_project}/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ({paths_to_project}/gulpfile.babel.js:8:1)
```

How can I use RxJS in gulp?

**Comment by blesh** [comment]
It seems like the second attempt should have worked. Do you have a replicating use-case we can work with? A repository with the error, perhaps?

**Comment by kwonoj** [comment]
Let me close this issue as inactive. If there's problem still persists, please feel freely reopen with additional details - best way would be reproducible repo.
