### ISSUE TITLE
Unable to compile with TypeScript 2.0.3 + Webpack 2.1.0-beta.25

### ISSUE THREAD

**Issue by mischkl** [ReactiveX/rxjs#2058]
**RxJS version:** 5.0.0-rc.1

**Code to reproduce:** Attempt to use any part of rxjs in code.

**Expected behavior:** It compiles.

**Actual behavior:** For simple imports, TypeScript complains about not finding various names within the rxjs type definition files. This is easily "fixable" by specifying the "skipLibCheck" compiler option. However, as soon as one attempts to use rxjs classes with basic operators such as `Observable.scan,`, the TypeScript compiler crashes with the following message: 

```
TypeError: Cannot read property 'id' of undefined
    at getNodeId (C:\workspace\myproject\node_modules\typescript\lib\typescript.js:16509:18)
    at getNodeLinks (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:16992:26)
    at checkExpressionCached (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:28851:25)
    at c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19466:25
    at Object.map (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:1240:29)
    at getTypeOfVariableOrParameterOrProperty (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19464:44)
    at getTypeOfSymbol (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19607:24)
    at getTypeOfAlias (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19590:23)
    at getTypeOfSymbol (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19619:24)
    at checkIdentifier (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:24671:24)
    at checkExpressionWorker (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:28932:28)
    at checkExpression (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:28912:42)
    at getBaseConstructorTypeOfClass (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:19726:43)
    at resolveAnonymousTypeMembers (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:20406:47)
    at resolveStructuredTypeMembers (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:20432:21)
    at getSignaturesOfStructuredType (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:20623:32)
    at getSignaturesOfType (c:\workspace\myproject\node_modules\typescript\lib\typescript.js:20633:20)
```

**Additional information:**
This is a project that is being migrated from ES5 to TS, so it consists of a mix of both kinds of files. .JS files are handled as CommonJS and bundled directly by Webpack, while ts-loader is configured to only handle .ts files. This is a setup that we have been using without issue for the last half year or so, which has so far enabled a smooth migration path with interoperability between JS and TS code.

Interestingly, if all *.d.ts files are deleted from the `rxjs` package and moved into `node_modules/@types/rxjs`, and the `Rx.d.ts` file there renamed to `index.d.ts`, then everything compiles and works just as expected.

If that turns out to be the only  way of getting such a hybrid project setup working with RxJS 5, perhaps it is worth considering publishing "pure" JS and "pure" typings for RxJS in addition to the "all-in-one" package. Then pure-JS or hybrid projects can consume those packages as needed, while pure-TS projects can rely on the pure-TS rxjs package.

Alternatively perhaps the issue lies more with TypeScript 2 and/or Webpack 2 and/or ts-loader. I have opened it here because this is the first package we've had trouble with so far (but also the first "all-in-one" package we've attempted to use).

For reference our configuration:

`tsconfig.json`:
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "allowJs": true,
        "outDir": "dist",
        "lib": [
            "dom",
            "es2016"
        ]
    },
    "include": [
        "src/**/*.ts"
    ]
}
```

`webpack.config.js`:
```js
module.exports = {
    entry: {
        index: './src/index'
    },
    output: {
        path: __dirname + '/dist',
        filename: '[name]-[hash].js'
    },
    resolve: {
        extensions: ['.js', '.ts']
    },
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loader: 'ts-loader'
            }
        ]
    }
};
```

**Comment by kwonoj** [comment]
one question -  is there any module ships type definition by default in your repo configuration? (As same as rx does, cjs module + have type difinition in module package)

**Comment by mischkl** [comment]
@kwonoj I'm pretty sure rxjs is the first one.

**Comment by jayphelps** [comment]
@mischkl is it possible for you provide a project for us to reproduce with? Perhaps remove all your private user code and then just push that copy to github. While not necessarily required, it's more likely we would find the issue quite quickly vs. making some guesses for you to try out 💃

**Comment by mischkl** [comment]
@kwonoj @jayphelps an example project sounds like a good idea, I probably won't get around to it for a couple of days but I will try to set it up as soon as I have a chance.

**Comment by mischkl** [comment]
I've set up a [demo project here](https://github.com/mischkl/demo-rxjs-typescript-webpack-error), demonstrating that the problem really does seem to lie with `ts-loader`, since everything works fine when using `awesome-typescript-loader`. Interestingly, the compiler only crashes when attempting to add the `map` operator. Simply using the built-in RxJS methods still results in type errors, but the code compiles nonetheless.

I'm therefore closing this issue and opening another one on `ts-loader`.
