### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by kentcdodds** [ReactiveX/rxjs#2151]
**RxJS version:**

`5.0.0-rc.4`

**Code to reproduce:**

```javascript
import Rx from 'rxjs/Rx'

Rx.Observable
  .from(['hi'])
  .flatMap(() => {}) // here's the key, nothing returned
  .subscribe({
    next: () => console.log('next'),
    error: err => console.error('something wrong happened:', err),
    complete: () => console.log('done'),
  })
```

**Expected behavior:**

Error that says something helpful. Something like:

> Must return a stream from `flatMap`, returned `undefined`

**Actual behavior:**

Error that says something confusing to newbies (like myself):

```
Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/util/subscribeToResult.js:45
    else if (typeof result[iterator_1.$$iterator] === 'function') {
                          ^

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.subscribeToResult (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/util/subscribeToResult.ts:58:27)
    at MergeMapSubscriber._innerSub (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/operator/mergeMap.ts:126:14)
    at MergeMapSubscriber._tryNext (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/operator/mergeMap.ts:122:10)
    at MergeMapSubscriber._next (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/operator/mergeMap.ts:106:12)
    at MergeMapSubscriber.Subscriber.next (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/Subscriber.ts:95:12)
    at ArrayObservable._subscribe (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/observable/ArrayObservable.ts:124:20)
    at ArrayObservable.Observable.subscribe (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/Observable.ts:98:21)
    at Observable._subscribe (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/Observable.ts:158:24)
    at MergeMapOperator.call (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/operator/mergeMap.ts:80:19)
    at Observable.subscribe (/Users/kdodds/Developer/kentcdodds.com/node_modules/rxjs/src/Observable.ts:96:16)
```

**Additional information:**

I imagine that it would be helpful to have this applied to many/most of the methods. As a beginner, seeing error messages like this is frustrating and makes it hard. Once you get used to the error message, you know what's going on, but if we want adoption of something with a steep learning curve as it is, it would be helpful to have more informative error messages :)

Thanks!

**Comment by trxcllnt** [comment]
💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯 💯

**Comment by david-driscoll** [comment]
I've been kicked by this in the past as well.

Really we just need to do a quick null check around https://github.com/ReactiveX/rxjs/blob/f51b8f9391ca6d751517a72fdabb05ad8c1013d8/src/util/subscribeToResult.ts#L26

**Comment by trxcllnt** [comment]
Yep, also [`unknown type returned`](https://github.com/ReactiveX/rxjs/blob/f51b8f9391ca6d751517a72fdabb05ad8c1013d8/src/util/subscribeToResult.ts#L79) is one of my least favorite errors. It's like, I know I forgot to return an Observable _somewhere_, but get no insight into which of my methods did it. Not to sure how to solve this either, which is why I'm complaining about it instead.

**Comment by oliviertassinari** [comment]
I wish this issue was prioritized, RxJS is such an awesome lib, all issues I have with it comes from **debugging**. I ended up adding defensive debugger everywhere the code could break:
``` jsx
if (observable === undefined) {
  debugger
}
```

**Comment by kentcdodds** [comment]
I'm going to go ahead and close this considering I'm not use RxJS. Feel free to reopen if someone wants to actually work on this.
