### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2216]
saw this bug just now, I don't think it's in my code. I am using rx-lite version  "rx-lite": "^4.0.8",

```console

(node:5828) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.error is not a function
TypeError: this.error is not a function
    at Rx.internals.AbstractObserver.AbstractObserver.onError (/home/oleg/WebstormProjects/oresoftware/cmd-queue/node_modules/rx-lite/rx.lite.js:1612:14)
(node:5828) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by kwonoj** [comment]
Hi, this repo is for RxJS v5, and given package version you've specified is v4, at https://github.com/Reactive-Extensions/RxJS. Let me close this issue, and suggest to report in corresponding repo.

**Comment by ORESoftware** [comment]
Thanks, so these two different organizations are differentiating by the
version of RxJS?

**Comment by kwonoj** [comment]
It is actually because v5 is complete rewrite of RxJS and have several breaking changes including its internals. Eventually it'll be migrated into new version, currently it's staying both.

**Comment by ORESoftware** [comment]
duh, I opened this issue before I even realize the difference, thanks @kwonoj !
