### ISSUE TITLE
Support question re: error message "no elements in sequence"

### ISSUE THREAD

**Issue by ORESoftware** [ReactiveX/rxjs#2262]
An unlikely bug, but thought I would ask.

With the following code in mind:

```js

const Rx = require('rxjs');

const obs = Rx.Observable.interval(100)
    .take(5)
    .map(function(v){
        console.log(v);
        return v;
    })
    .reduce(function (prev, curr) {
        return prev.concat(curr);
    },[])
    .last(function (results) {
        return results;
    })
    .map(function(v){
        console.log(v);
    });


obs.subscribe();
```

if we remove the second map call, and we comment out the return statement, like so:

```js
const Rx = require('rxjs');

const obs = Rx.Observable.interval(100)
    .take(5)
    .map(function(v){
        console.log(v);
        return v;
    })
    .reduce(function (prev, curr) {
        return prev.concat(curr);
    },[])
    .last(function (results) {
        console.log('results => ', results);
        // return results;
    });


obs.subscribe();

```
then if we run this new code, we get an error:

```
/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/scheduler/AsyncScheduler.js:45
            throw error;
            ^
EmptyError: no elements in sequence
    at new EmptyError (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/util/EmptyError.js:20:26)
    at LastSubscriber._complete (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/operator/last.js:114:31)
    at LastSubscriber.Subscriber.complete (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/Subscriber.js:114:18)
    at ReduceSubscriber._complete (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/operator/reduce.js:118:26)
    at ReduceSubscriber.Subscriber.complete (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/Subscriber.js:114:18)
    at MapSubscriber.Subscriber._complete (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.complete (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/Subscriber.js:114:18)
    at TakeSubscriber._next (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/operator/take.js:82:34)
    at TakeSubscriber.Subscriber.next (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/Subscriber.js:89:18)
    at AsyncAction.IntervalObservable.dispatch [as work] (/home/oleg/WebstormProjects/oresoftware/observable-persistent-queue/node_modules/rxjs/observable/IntervalObservable.js:70:20)
```

is that error expected, and why does it occur? Does this error need to happen?

**Comment by ORESoftware** [comment]
If there error message does/should need to be there, then I would just ask for a less cryptic error message(?)

**Comment by trxcllnt** [comment]
@ORESoftware you're seeing this error because your `last` predicate always returns undefined. See the [docs for the `last` predicate here](https://github.com/ReactiveX/rxjs/blob/master/src/operator/last.ts#L38).

I noticed in this issue and in #2265, it seems like the function you pass to the last operator in your sequence (`last` in this case, `map` in the other issue) should instead be the first argument to `subscribe`. Alternatively, if you want to do a side-effect for every subscription without affecting the sequence, you can end the sequence with a call to `do()`.

**Comment by ORESoftware** [comment]
Ok thanks the tips! much appreciated

**Comment by ORESoftware** [comment]
@trxcllnt this following short and sweet question is related - do you think you have an answer for it?
http://stackoverflow.com/questions/41527460/cannot-extract-value-from-concatenated-observable
