### ISSUE TITLE
Different src permissions in 5.3.0?

### ISSUE THREAD

**Issue by returnlytom** [ReactiveX/rxjs#2522]
**RxJS version:**
5.3.0

**Code to reproduce:**
1. Install / upgrade to `rxjs@latest` (see _package.json_ below)
2. Compile with webpack

**Expected behavior:**
It builds successfully. (It was before on 5.2.0).

**Actual behavior:**
```
[at-loader]: Child process failed to process the request:  { Error: EACCES: permission denied, open '/var/app/ondeck/node_modules/rxjs/Observable.d.ts'
```

**Additional information:**

A few notes:
* this is occurring in our Elasticbeanstalk box, so it could be due to the environment of that machine
* This temporary workaround worked:

`chmod 777 node_modules/rxjs/* -R`

_package.json_
```js
{
  "devDependencies": {
    "@types/node": "latest",
    "awesome-typescript-loader": "latest",
    "babel-core": "latest",
    "babel-loader": "latest",
    "babel-preset-env": "latest",
    "glob": "latest",
    "path-complete-extname": "latest",
    "rails-erb-loader": "latest",
    "ts-helpers": "latest",
    "ts-node": "latest",
    "tslint": "latest",
    "typescript": "latest",
    "webpack": "latest",
    "webpack-dev-server": "latest",
    "webpack-merge": "latest"
  },
  "dependencies": {
    "@angular/common": "next",
    "@angular/compiler": "next",
    "@angular/core": "next",
    "@angular/forms": "next",
    "@angular/http": "next",
    "@angular/platform-browser": "next",
    "@angular/platform-browser-dynamic": "next",
    "@angular/router": "next",
    "angulartics2": "latest",
    "classlist-polyfill": "latest",
    "core-js": "latest",
    "es6-shim": "latest",
    "intl": "latest",
    "mobx": "latest",
    "mobx-angular": "latest",
    "raven-js": "latest",
    "rxjs": "latest",
    "webstorage-polyfill": "latest",
    "zone.js": "latest"
  }
}
```

**Comment by kwonoj** [comment]
Type definitions are generated by compiler and we don't apply specific permissions afterward. /cc @benlesh just in case dev system published package might have changed? But seems bit odd. 

Not sure about elasticbeanstalk env, do you possibly have isolated repo can reproduce issue?

**Comment by returnlytom** [comment]
@kwonoj thanks for the prompt response

Investigating the elasticbeanstalk env and permissions, and in the meantime will see if I can repro with a smaller repo.

**Comment by returnlytom** [comment]
Following up to confirm that pegging rxjs at 5.2.0 allowed our build to finish successfully. Continuing to investigate EB environment.

**Comment by utkuturunc** [comment]
On AWS Lambda I started getting the following error after updating to 5.3.0. Reverting back to 5.2.0 solved the issue.

```
{ Error: EACCES: permission denied, open '/var/task/node_modules/rxjs/Rx.js'
at Error (native)
at Object.fs.openSync (fs.js:640:18)
at Object.fs.readFileSync (fs.js:508:33)
at Object.Module._extensions..js (module.js:578:20)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
errno: -13,
code: 'EACCES',
syscall: 'open',
path: '/var/task/node_modules/rxjs/Rx.js' },
```

**Comment by kwonoj** [comment]
I think this issue is now resolved in 5.3.1, will leave this issue opened couple of day more to get feedback if it still does have issues.

**Comment by about-code** [comment]
Just installed 5.3.1 locally on a Linux machine using yarn. Files continue to be installed with mask 640 (-rw-r-----) while for 5.2.0 they will be installed with 644 (-rw-r--r--).  There must be something wrong with the way the *tar.gz* archive published on npmjs.com was created.

**Comment by kwonoj** [comment]
I'm adding @benlesh for visibility.

**Comment by fdubost** [comment]
I have the same issue (#2687). Is there a solution ?

**Comment by returnlytom** [comment]
@fdubost copying a salient comment of yours from the dupe issue:

>Additional information: This is problematic for us because the user who deploys the code and installs the dependencies is not the same as the one who runs the server

We had the same problem and still have rxjs pegged at 5.2.0 in our prod build.

**Comment by benlesh** [comment]
I have no idea how to reproduce this or what could be causing it, and therefor I have no idea how I could attempt to fix it. I've published the last few from an Ubuntu machine, but that's all I can think of that's different.

**Comment by fdubost** [comment]
Reproducing the problem is easy 🎎 :
```shell
$ mkdir toto
$ cd toto
$ yarn add rxjs
$ ls -l node_modules/rxjs/
total 528
-rw-r-----    1 fdubost  staff    433 15 jui 00:09 AsyncSubject.d.ts
-rw-r-----    1 fdubost  staff   1797 15 jui 00:09 AsyncSubject.js
-rw-r-----    1 fdubost  staff   1360 15 jui 00:09 AsyncSubject.js.map
-rw-r-----    1 fdubost  staff    410 15 jui 00:09 BehaviorSubject.d.ts
-rw-r-----    1 fdubost  staff   1666 15 jui 00:09 BehaviorSubject.js
-rw-r-----    1 fdubost  staff   1069 15 jui 00:09 BehaviorSubject.js.map
-rw-r-----    1 fdubost  staff    537 15 jui 00:09 InnerSubscriber.d.ts
-rw-r-----    1 fdubost  staff   1289 15 jui 00:09 InnerSubscriber.js
-rw-r-----    1 fdubost  staff    827 15 jui 00:09 InnerSubscriber.js.map
-rw-r-----    1 fdubost  staff  11064 15 jui 00:09 LICENSE.txt
-rw-r-----    1 fdubost  staff   3145 15 jui 00:09 Notification.d.ts
-rw-r-----    1 fdubost  staff   4747 15 jui 00:09 Notification.js
-rw-r-----    1 fdubost  staff   2382 15 jui 00:09 Notification.js.map
-rw-r-----    1 fdubost  staff   3060 15 jui 00:09 Observable.d.ts
-rw-r-----    1 fdubost  staff  11407 15 jui 00:09 Observable.js
-rw-r-----    1 fdubost  staff   3124 15 jui 00:09 Observable.js.map
-rw-r-----    1 fdubost  staff    737 15 jui 00:09 Observer.d.ts
-rw-r-----    1 fdubost  staff    193 15 jui 00:09 Observer.js
-rw-r-----    1 fdubost  staff    259 15 jui 00:09 Observer.js.map
-rw-r-----    1 fdubost  staff    192 15 jui 00:09 Operator.d.ts
-rw-r-----    1 fdubost  staff     50 15 jui 00:09 Operator.js
-rw-r-----    1 fdubost  staff    105 15 jui 00:09 Operator.js.map
-rw-r-----    1 fdubost  staff    509 15 jui 00:09 OuterSubscriber.d.ts
-rw-r-----    1 fdubost  staff   1107 15 jui 00:09 OuterSubscriber.js
-rw-r-----    1 fdubost  staff    589 15 jui 00:09 OuterSubscriber.js.map
-rw-r-----    1 fdubost  staff   7167 15 jui 00:09 README.md
-rw-r-----    1 fdubost  staff    598 15 jui 00:09 ReplaySubject.d.ts
-rw-r-----    1 fdubost  staff   3859 15 jui 00:09 ReplaySubject.js
-rw-r-----    1 fdubost  staff   3163 15 jui 00:09 ReplaySubject.js.map
-rw-r-----    1 fdubost  staff   7645 15 jui 00:09 Rx.d.ts
-rw-r-----    1 fdubost  staff   9651 15 jui 00:09 Rx.js
-rw-r-----    1 fdubost  staff   5002 15 jui 00:09 Rx.js.map
-rw-r-----    1 fdubost  staff   2229 15 jui 00:09 Scheduler.d.ts
-rw-r-----    1 fdubost  staff   1885 15 jui 00:09 Scheduler.js
-rw-r-----    1 fdubost  staff    653 15 jui 00:09 Scheduler.js.map
-rw-r-----    1 fdubost  staff   1389 15 jui 00:09 Subject.d.ts
-rw-r-----    1 fdubost  staff   5613 15 jui 00:09 Subject.js
-rw-r-----    1 fdubost  staff   4526 15 jui 00:09 Subject.js.map
-rw-r-----    1 fdubost  staff    447 15 jui 00:09 SubjectSubscription.d.ts
-rw-r-----    1 fdubost  staff   1401 15 jui 00:09 SubjectSubscription.js
-rw-r-----    1 fdubost  staff    978 15 jui 00:09 SubjectSubscription.js.map
-rw-r-----    1 fdubost  staff   3011 15 jui 00:09 Subscriber.d.ts
-rw-r-----    1 fdubost  staff   9695 15 jui 00:09 Subscriber.js
-rw-r-----    1 fdubost  staff   6448 15 jui 00:09 Subscriber.js.map
-rw-r-----    1 fdubost  staff   2801 15 jui 00:09 Subscription.d.ts
-rw-r-----    1 fdubost  staff   8183 15 jui 00:09 Subscription.js
-rw-r-----    1 fdubost  staff   4961 15 jui 00:09 Subscription.js.map
drwxr-xr-x    4 fdubost  staff    136 21 jui 23:32 add
drwxr-xr-x    5 fdubost  staff    170 21 jui 23:32 bundles
drwxr-xr-x  141 fdubost  staff   4794 21 jui 23:32 observable
drwxr-xr-x  308 fdubost  staff  10472 21 jui 23:32 operator
-rw-r-----    1 fdubost  staff   4932 15 jui 00:09 package.json
drwxr-xr-x   44 fdubost  staff   1496 21 jui 23:32 scheduler
drwxr-xr-x   26 fdubost  staff    884 21 jui 23:32 src
drwxr-xr-x   11 fdubost  staff    374 21 jui 23:32 symbol
drwxr-xr-x   20 fdubost  staff    680 21 jui 23:32 testing
drwxr-xr-x   86 fdubost  staff   2924 21 jui 23:32 util
```

**Comment by about-code** [comment]
Meanwhile I've upgraded to node 8 and yarn 0.24.5. `rxjs@5.3.0` and `rxjs@5.3.1` were installed with correct permissions (622) -rw-r--r--. It doesn't seem to be an issue with rxjs. There's was a [bug in yarn](https://github.com/yarnpkg/yarn/issues/1143) fixed end of May which seems to be related to this one here. So I suggest to everyone facing the issue to update yarn and try again.

**Comment by returnlytom** [comment]
@about-code Confirmed working with `yarn@0.24.6` and `rxjs@5.4.0`, thanks!!

**Comment by fdubost** [comment]
I have the same issue with yarn@0.24.6, rxjs@5.4.1 and node@8.1.2 (idem with node@7.9.0) 😥

**Comment by fdubost** [comment]
Oh it seems to work after a `yarn cache clean` 🙄

**Comment by returnlytom** [comment]
@about-code thanks, closing the issue :)
