### ISSUE TITLE
Frame of TestScheduler does not start from 0(zero) in every unit test?

### ISSUE THREAD

**Issue by mrdulin** [ReactiveX/rxjs#2757]
**RxJS version:** `^5.4.2`

**Code to reproduce:**

`__tests__/observables/interval.test.ts`:

```ts
import { Observable, TestScheduler } from 'rxjs';
import { hot, rxTestScheduler } from '../helpers/marble-testing';

describe('Observable.interval', () => {

  it('should create an observable emitting periodically', () => {
    const e1 = Observable.interval(20, rxTestScheduler)
      .take(6)
      .concat(Observable.never());
    const expected = '--a-b-c-d-e-f-';
    const values = { a: 0, b: 1, c: 2, d: 3, e: 4, f: 5 };
    rxTestScheduler.expectObservable(e1).toBe(expected, values);
    rxTestScheduler.flush();
  });

  it('should set up an interval', () => {
    const e1 = Observable.interval(100, rxTestScheduler);
    const expected = '----------0---------1---------2---------3---------4---------5---------6-----';
    rxTestScheduler.expectObservable(e1).toBe(expected, [0, 1, 2, 3, 4, 5, 6]);
    rxTestScheduler.flush();
  });

});
```
test result:

```bash
Difference:

    - Expected
    + Received

     Array [
       Object {
    -    "frame": 100,
    +    "frame": 220,
         "notification": Notification {
           "error": undefined,
           "hasValue": true,
           "kind": "N",
           "value": 0,
         },
       },
       Object {
    -    "frame": 200,
    +    "frame": 320,
         "notification": Notification {
           "error": undefined,
           "hasValue": true,
           "kind": "N",
           "value": 1,
         },
       },
       Object {
    -    "frame": 300,
    +    "frame": 420,
         "notification": Notification {
           "error": undefined,
           "hasValue": true,
           "kind": "N",
           "value": 2,
         },
       },
       Object {
    -    "frame": 400,
    +    "frame": 520,
         "notification": Notification {
           "error": undefined,
           "hasValue": true,
           "kind": "N",
           "value": 3,
         },
       },
       Object {
    -    "frame": 500,
    +    "frame": 620,
         "notification": Notification {
           "error": undefined,
           "hasValue": true,
           "kind": "N",
           "value": 4,
         },
       },
       Object {
    -    "frame": 600,
    +    "frame": 720,
         "notification": Notification {
           "error": undefined,
           "hasValue": true,
           "kind": "N",
           "value": 5,
         },
       },
    -  Object {
    -    "frame": 700,
    -    "notification": Notification {
    -      "error": undefined,
    -      "hasValue": true,
    -      "kind": "N",
    -      "value": 6,
    -    },
    -  },
     ]

      at TestScheduler.assertDeepEqual (src/demos-rxjs-v5/__tests__/helpers/marble-testing.ts:8:80)
      at TestScheduler.Object.<anonymous>.TestScheduler.flush (node_modules/rxjs/src/testing/TestScheduler.ts:135:12)
      at Object.<anonymous> (src/demos-rxjs-v5/__tests__/observables/interval.test.ts:23:4)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Expected behavior:**

I think when I call the method `flush` of `TestScheduler` at the end of first unit test,  the frame should be start from `0` in the next unit test.

**Actual behavior:**

frame start from `220`, when I delete the first unit test, the second unit test pass.

**Additional information:**

`__tests__/helpers/mable -testing.ts`:

```ts
import { HotObservable } from 'rxjs/testing/HotObservable';
import { ColdObservable } from 'rxjs/testing/ColdObservable';
import { TestScheduler } from 'rxjs';

const rxTestScheduler = new TestScheduler((a, b) => expect(a).toEqual(b));

function hot(marbles: string, values?: any, error?: any): HotObservable<any> {
  return rxTestScheduler.createHotObservable.apply(rxTestScheduler, arguments);
}

function cold(marbles: string, values?: any, error?: any): ColdObservable<any> {
  return rxTestScheduler.createColdObservable.apply(rxTestScheduler, arguments);
}

export {
  rxTestScheduler,
  hot,
  cold
};

```

**Comment by kwonoj** [comment]
Current design of testscheduler is intended to be used only once, for each test you need to instantiate new one either manually or via `beforeEach`. This is mostly to avoid possible side effects between test cases.

**Comment by mrdulin** [comment]
@kwonoj Ok. Thanks. I know it. Does spec files do some custom setup of this repo? I mean,  this repo's test files do some work like `beforeEach`?
