### ISSUE TITLE
angular5 build fail

### ISSUE THREAD

**Issue by yooRabbit** [ReactiveX/rxjs#3060]
**RxJS version:5.5.2

**Code to reproduce:**

**Expected behavior:**
Build with angular5,and run ng build --prod --aot.

**Actual behavior:**
```
ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:44563:16)
    at checkSourceElement (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:41990:21)
    at checkDeferredNodes (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:46828:25)
    at checkSourceFileWorker (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:46863:17)
    at checkSourceFile (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:46842:13)
    at Object.forEach (D:\yoo\project\ngx-seed\node_modules\typescript\lib\typescript.js:1506:30)
 @ ./node_modules/rxjs/observable/bindCallback.js 2:32-68
 @ ./node_modules/rxjs/add/observable/bindCallback.js
 @ ./node_modules/rxjs/Rx.js
 @ ./src/polyfills.ts
 @ multi ./src/polyfills.ts
```

**Additional information:**
Is this cased because of my package version are not correct?
here my package.json
```
"dependencies": {
    "@angular/animations": "5.0.0",
    "@angular/cdk": "5.0.0-rc0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/material": "5.0.0-rc0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/platform-server": "5.0.0",
    "@angular/router": "5.0.0",
    "@types/jquery": "3.2.16",
    "@types/node": "6.0.90",
    "core-js": "2.5.1",
    "css-loader": "^0.28.7",
    "flatpickr": "4.0.7",
    "font-awesome": "^4.7.0",
    "hammerjs": "2.0.8",
    "jquery": "3.2.1",
    "ng2-dragula": "^1.5.0",
    "ngx-webstorage": "^2.0.0",
    "node-sass": "^4.6.0",
    "rxjs": "5.5.2",
    "typescript": "^2.4.2",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/language-service": "5.0.0",
    "@types/jasmine": "2.6.3",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "8.0.50",
    "codelyzer": "4.0.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.2.0",
    "ts-node": "3.3.0",
    "tslint": "5.8.0"
  }
```
Thanks for help

**Comment by androidseb25** [comment]
The same issue on my side :(

**Comment by androidseb25** [comment]
ok i fixed it on my side the only think what i did is updated typescript to 2.6.1

**Comment by yooRabbit** [comment]
@androidseb25  I also fix this problem with this method，but It still warning this:
```
@angular/compiler-cli@5.0.0 requires typescript@'>=2.4.2 <2.5.0' but 2.6.1 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.4.2 <2.5.0'

To disable this warning run "ng set warnings.typescriptMismatch=false".
```
wait for the principle of explanation

**Comment by androidseb25** [comment]
@yooRabbit that's only a warning
in my project i have no problem with the debugging or something else you can ignore the warning

**Comment by Lakston** [comment]
From the angular guide to upgrade they are recommending an exact version of typescript, in case someone comes by for info I'll post it here : `npm install typescript@2.4.2 --save-exact`

**Comment by yooRabbit** [comment]
`npm install --save typescript@2.4.2 `can fix this problem.

**Comment by finalxcode** [comment]
@yooRabbit thanks
