### ISSUE TITLE
You provided xxxx where a stream was expected. will be generated in 6.0.0-uncanny-rc.7

### ISSUE THREAD

**Issue by MSakamaki** [ReactiveX/rxjs#3573]
**RxJS version:**
 - 6.0.0-ucandoit-rc.6
 - 6.0.0-uncanny-rc.7

**Code to reproduce:**

 + typescript code

```typescript

import { range, from, concat } from 'rxjs';
import { reduce } from 'rxjs/internal/operators';

concat(
  from(['A','B','C']),
  reduce(()=> { 
    console.log('reduce?');
  }),
).subscribe(
  r => console.log('next', r),
  e => console.error('error', e),
  () => console.log('CMPLITE'),
);

```

**Expected behavior:**

version wants the same behavior in `6.0.0-ucandoit-rc.6` and `6.0.0-uncanny-rc.7`

**Actual behavior:**

Version `6.0.0-uncanny-rc.7` raises the following exceptions

```sh
> ts-node index.ts

next A
next B
next C
error TypeError: You provided 'function reduceOperatorFunction(source) {
        return pipe_1.pipe(scan_1.scan(function (acc, value, index) {
            return accumulator(acc, value, index + 1);
        }), takeLast_1.takeLast(1))(source);
    }' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.exports.subscribeTo (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/util/subscribeTo.ts:37:11)
    at Object.subscribeToResult (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/util/subscribeToResult.ts:18:10)
    at MergeMapSubscriber._innerSub (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/operators/mergeMap.ts:139:14)
    at MergeMapSubscriber._tryNext (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/operators/mergeMap.ts:135:10)
    at MergeMapSubscriber._next (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/operators/mergeMap.ts:119:12)
    at MergeMapSubscriber.Subscriber.next (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/Subscriber.ts:102:12)
    at Observable._subscribe (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/util/subscribeToArray.ts:9:16)
    at Observable._trySubscribe (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/Observable.ts:216:19)
    at Observable.subscribe (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/Observable.ts:198:87)
    at MergeMapOperator.call (/Users/test/project/work/rx-test/node_modules/rxjs/src/internal/operators/mergeMap.ts:94:19)

```

**Additional information:**

The related issues are as follows.
https://github.com/angular/angular-cli/issues/10336

From `6.0.0-uncanny-rc.7`, the following process seems to fail.

It seems to be caused by this patch https://github.com/ReactiveX/rxjs/pull/3562

The cause of the above issues to be due to a [similar implementation](Https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/tools/workflow/node-workflow.ts#L180) on devkit side

**Comment by cartant** [comment]
`reduce` returns an [operator function](https://github.com/ReactiveX/rxjs/blob/6.0.0-uncanny-rc.7/src/internal/operators/reduce.ts#L9-L11) that expects to be passed an `Observable`; it does not return an `ObservableInput`, so the code in the issue's snippet is incorrect.

PR #3562 has exposed an error.

**Comment by filipesilva** [comment]
@cartant should this be a compile-time error when using the rxjs typings?

**Comment by cartant** [comment]
@filipesilva Yes, it should be, but I suspect that no compile-time error is effected because of https://github.com/Microsoft/TypeScript/issues/18757.

**Comment by filipesilva** [comment]
Got it. Yeah that sounds like an unfortunate situation :/

**Comment by benlesh** [comment]
@cartant's answer here is correct. Closing this issue.
