### ISSUE TITLE
ReferenceError: WebSocket is not defined (6.1.0)

### ISSUE THREAD

**Issue by krismrp** [ReactiveX/rxjs#3692]
**RxJS version:** 6.1.0

**Code to reproduce:**
```javascript
const { webSocket } = require("rxjs/websocket");
const w3cwebsocket = require("websocket").w3cwebsocket;

webSocket({
  url: 'ws://foobar',
  WebSocketCtor: w3cwebsocket
});
```

**Expected behavior:**
Should not error when given a WebSocket constructor.

**Actual behavior:**
```
            config.WebSocketCtor = WebSocket;
                                   ^

ReferenceError: WebSocket is not defined
    at new WebSocketSubject (E:\CODE\Github\[REMOVED]\node_modules\rxjs\internal\observable\dom\WebSocketSubject.js:49:36)
    at webSocket (E:\CODE\Github\[REMOVED]\node_modules\rxjs\internal\observable\dom\webSocket.js:43:12)
    at Object.<anonymous> (E:\CODE\Github\[REMOVED]\index.js:4:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
```

**Comment by waitingsong** [comment]
try
`const websocket = require('rxjs/websocket');`

**Comment by krismrp** [comment]
I still get the same error message, can you confirm that the above code works for you?

**Comment by waitingsong** [comment]
yes. it works .

**Comment by krismrp** [comment]
Hm, still the same issue. Didn't have any problems with 5.x version.

**Comment by bbonnet** [comment]
I think that should fix the issue, can someone help verify? https://github.com/ReactiveX/rxjs/pull/3694

**Comment by krismrp** [comment]
@bbonnet I'll gladly do that, but how exactly? I was able to get install your pull request with Yarn, but everything went downhill from there. 😕

**Comment by bbonnet** [comment]
@krismrp Did you get a specific error when everything went downhill? lol I think you should just be able to pin to that branch and pull it down into your app but I'm not 100% sure
