### ISSUE TITLE
Failed to load resource:  rxjs-compat/observable/forkJoin/:1 Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by ndlos85** [ReactiveX/rxjs#3752]
getting  below error while running angular program
error log :index.html:18 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:61560/src/rxjs-compat/observable/forkJoin
	Error: XHR error (404 Not Found) loading http://localhost:61560/src/rxjs-compat/observable/forkJoin
	    at XMLHttpRequest.wrapFn (http://localhost:61560/node_modules/zone.js/dist/zone.js:1188:39)
	    at ZoneDelegate.invokeTask (http://localhost:61560/node_modules/zone.js/dist/zone.js:421:31)
	    at Zone.runTask (http://localhost:61560/node_modules/zone.js/dist/zone.js:188:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:61560/node_modules/zone.js/dist/zone.js:496:34)
	    at invokeTask (http://localhost:61560/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:61560/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:61560/src/rxjs-compat/observable/forkJoin as "rxjs-compat/observable/forkJoin" from http://localhost:61560/node_modules/rxjs/observable/forkJoin.js
	    at XMLHttpRequest.wrapFn (http://localhost:61560/node_modules/zone.js/dist/zone.js:1188:39)
	    at ZoneDelegate.invokeTask (http://localhost:61560/node_modules/zone.js/dist/zone.js:421:31)
	    at Zone.runTask (http://localhost:61560/node_modules/zone.js/dist/zone.js:188:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:61560/node_modules/zone.js/dist/zone.js:496:34)
	    at invokeTask (http://localhost:61560/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:61560/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:61560/src/rxjs-compat/observable/forkJoin as "rxjs-compat/observable/forkJoin" from http://localhost:61560/node_modules/rxjs/observable/forkJoin.js

**RxJS version:**
6.2.0

**Comment by kwonoj** [comment]
maybe related to https://github.com/ReactiveX/rxjs/issues/3691

**Comment by ndlos85** [comment]
actually i ma working on angualr Demo application . we used ngModel tag to Bind data to a input box . for ngModel to be recognized ,we need to import FormsModule . Then the Error started to appear on importing FormsModule.

**Comment by benlesh** [comment]
Cannot reproduce.
