### ISSUE TITLE
Mocking fromEvent in rxjs6 

### ISSUE THREAD

**Issue by rsirs** [ReactiveX/rxjs#3848]
### Spy on fromEvent haven't been called

```js
spyOn(Observable, 'fromEvent)
expect(Observable.fromEvent).toHaveBeenCalled();
```

Above mentioned piece of code is not working for rxjs6 version but working on rxjs5 

## Work arounds to make this work but failed

```js
import {fromEvent} from 'rxjs'

let Obj = { observableFromEvent: fromEvent }
spyOn(Obj, 'observableFromEvent')
expect(observableFromEvent).toHaveBeenCalled();

/* jasmine test case failed with spy hasn't been called */
```

```js
import * as rxjs form 'rxjs'

spyOn(rxjs, 'fromEvent')
expect(rxjs.fromEvent).toHaveBeenCalled();

/* Test case failed with not setter or non writable fromEvent */

<!-- Descrbe the issue in detail here -->

**Comment by benlesh** [comment]
So you want to spy on `fromEvent`?

You should be able to just import everything, and spy on that:

```ts
import * as rxjs from 'rxjs';

spyOn(rxjs, 'fromEvent')
```

**Comment by rsirs** [comment]
@benlesh I already did  but, Jasmine is complaining [method_name] is not declared writable or has no setter since es6 imports are constants.

**Comment by aniruddhadas9** [comment]
After using @benlesh idea, I am getting below 

```
	Error: <spyOn> : fromEvent is not declared writable or has no setter
	Usage: spyOn(<object>, <methodName>)
	    at Object.<anonymous> src/app/app.component.spec.ts:215:7)
	    at TestBed.push../node_modules/@angular/core/fesm5/testing.js.TestBed.execute node_modules/@angular/core/fesm5/testing.js:1074:1)
	    at Object.<anonymous> node_modules/@angular/core/fesm5/testing.js:1225:29)
	    at Object.<anonymous> node_modules/zone.js/dist/fake-async-test.js:593:1)
	    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke node_modules/zone.js/dist/zone.js:388:1)
	    at ProxyZoneSpec.push../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke node_modules/zone.js/dist/proxy.js:128:1)
	    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke node_modules/zone.js/dist/zone.js:387:1)

```

**Comment by kksevta** [comment]
Getting same error after importing everything.

**Comment by hannaraczek** [comment]
I believe I figured it out!! (Pardon the exclamation, but I have been banging my head against this for ages). I'm not sure how you use `fromEvent()`, but if you just do `foo = fromEvent(element, 'eventName')`, this might be the answer.

Turns out, there are two `fromEvent` methods--one that's from rxjs, and one that's from Observable. You'll want the Observable one.

`spyOn(Observable, 'fromEvent')
expect(Observable.fromEvent).toHaveBeenCalled();`
worked for me, but in my code, instead of `fromEvent(element, 'eventName`), I did `Observable.fromEvent(element, `eventName`). This allowed me to spy on `fromEvent` and do what I wanted with it. 

Hope this helps!

**Comment by bfaulk96** [comment]
@hannaraczek `Observable.fromEvent()` is from RXJS 5, they switched to just `fromEvent()` in RXJS 6... As this question is specifically for getting RXJS 6 to work, that is not a viable solution here.

**Comment by martinsik** [comment]
I know this is a lame solution but maybe just wrapping `fromEvent` would be enough (I didn't test this):

```
import {fromEvent as realFromEvent} from 'rxjs'

...

it('test', () => {
  let called = false;
  const fromEvent = (...args: any[]) => {
    const o = realFromEvent(...args);
    called = true;
    return o;
  };

  ... 

  expect(called).toBeTruthy(); // or whatever...
})
```
