### ISSUE TITLE
CORS is not supported by your browser

### ISSUE THREAD

**Issue by EvanCarroll** [ReactiveX/rxjs#3978]
Write up on https://stackoverflow.com/questions/51603801/using-rx-js-i-get#51603802

## Bug Report

Still getting

> CORS is not supported by your browser

Can't comment on #1711 (which documents this ug)

**Current Behavior**

```
Error: CORS is not supported by your browser
    at getCORSRequest (/node_modules/rxjs/internal/observable/dom/AjaxObservable.js:27:15)
    at Object.createXHR (/node_modules/rxjs/internal/observable/dom/AjaxObservable.js:93:43)
    at Object.tryCatcher (/node_modules/rxjs/internal/util/tryCatch.js:7:31)
    at AjaxSubscriber.send (/node_modules/rxjs/internal/observable/dom/AjaxObservable.js:159:50)
    at new AjaxSubscriber (/node_modules/rxjs/internal/observable/dom/AjaxObservable.js:147:15)
    at AjaxObservable._subscribe (/node_modules/rxjs/internal/observable/dom/AjaxObservable.js:116:16)
    at AjaxObservable.Observable._trySubscribe (/node_modules/rxjs/internal/Observable.js:43:25)
    at AjaxObservable.Observable.subscribe (/node_modules/rxjs/internal/Observable.js:29:22)
    at Object.<anonymous> (/index.js:17:7)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```

**Environment**
- Runtime: Node w/ rxjs6
- RxJS version:      "rxjs": "^6.2.2",

**Possible Solution**

Add 

```
createXHR: function () {
  return new XMLHttpRequest();
}
```

**Comment by benlesh** [comment]
Hi @EvanCarroll, I've answered your question on stackoverflow.

You need to add your custom `createXHR` function onto each config passed to the ajax call.

```ts
function createXHR() {
  return new CustomXHRImpl();
}

const foo$ = ajax({
  createXHR,
  url: 'whatever',
});
```
