### ISSUE TITLE
[Typescript-Angular] Generate client code with rxjs for Angular6+

### ISSUE THREAD

**Issue by twopelu** [ReactiveX/rxjs#4606]
## Feature Request

The client code generated for typescript-angular uses old version of rxjs which is not supported in Angular6+ projects. To make it work you have to manually install rxjs-compat package with npm: `npm install rxjs-compat`.

**Describe the solution you'd like**
Generate the client code with the latest versions of rxjs for Angular6+.

**Additional context**

Find attached the api definition in yml:

[openapi.zip](https://github.com/ReactiveX/rxjs/files/2923310/openapi.zip)

Code generated with Swagger Hub:

[typescript-angular-client-generated.zip](https://github.com/ReactiveX/rxjs/files/2923311/typescript-angular-client-generated.zip)

Error in `ng build`:

```
BUILD ERROR
diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.
../node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
diary-shit-client-lib/src/lib/api/diary.service.ts(19,10): error TS2305: Module '"D:/DANI/vscode/dairy-shit-libs/node_modules/rxjs/Observable"' has no exported member 'Observable'.

Error: diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.
../node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
diary-shit-client-lib/src/lib/api/diary.service.ts(19,10): error TS2305: Module '"D:/DANI/vscode/dairy-shit-libs/node_modules/rxjs/Observable"' has no exported member 'Observable'.

    at Object.<anonymous> (D:\DANI\vscode\dairy-shit-libs\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (D:\DANI\vscode\dairy-shit-libs\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>

diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.
../node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
diary-shit-client-lib/src/lib/api/diary.service.ts(19,10): error TS2305: Module '"D:/DANI/vscode/dairy-shit-libs/node_modules/rxjs/Observable"' has no exported member 'Observable'.
```

**Comment by twopelu** [comment]
Apologies, I have created in this repo by error. I close it, please delete.
