### ISSUE TITLE
[Typescript-Angular] 

### ISSUE THREAD

**Issue by twopelu** [ReactiveX/rxjs#4607]
## Bug report

The client code generated for typescript-angular has errors and it does not compile, there are closing braces missing in some files. To make it work you have to manually edit the files.

**Describe the solution you'd like**
Fix the code generated so that it compiles.

**Additional context**

Find attached the api definition in yml:

[openapi.zip](https://github.com/ReactiveX/rxjs/files/2923313/openapi.zip)

Code generated with Swagger Hub:

[typescript-angular-client-generated.zip](https://github.com/ReactiveX/rxjs/files/2923314/typescript-angular-client-generated.zip)

Error in ng build:

```
BUILD ERROR
diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.

Error: diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.

    at Object.<anonymous> (D:\DANI\vscode\dairy-shit-libs\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (D:\DANI\vscode\dairy-shit-libs\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>

diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.

Error: diary-shit-client-lib/src/lib/api/diary.service.ts(229,1): error TS1005: '}' expected.

    at Object.<anonymous> (D:\DANI\vscode\dairy-shit-libs\node_modules\ng-packagr\lib\ngc\compile-source-files.js:65:19)
    at Generator.next (<anonymous>)
    at fulfilled (D:\DANI\vscode\dairy-shit-libs\node_modules\ng-packagr\lib\ngc\compile-source-files.js:4:58)
    at <anonymous>
```

**Comment by twopelu** [comment]
Apologies, I have created in this repo by error. I close it, please delete.
