### ISSUE TITLE
ConnectableObservable: TypeError: this.subjectFactory is not a function

### ISSUE THREAD

**Issue by Frikki** [ReactiveX/RxJS#568]
### Overview

Error and stack trace

```shell
/home/frikki/test/node_modules/@reactivex/rxjs/dist/cjs/observables/ConnectableObservable.js:39
        return this.subject = this.subjectFactory();
                                   ^

TypeError: this.subjectFactory is not a function
    at ConnectableObservable._getSubject (/home/frikki/test/node_modules/@reactivex/rxjs/dist/cjs/observables/ConnectableObservable.js:39:36)
    at ConnectableObservable.connect (/home/frikki/test/node_modules/@reactivex/rxjs/dist/cjs/observables/ConnectableObservable.js:48:46)
    at Object.<anonymous> (/home/frikki/test/script.js:6:39)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

### Motivation

In earlier versions of RxJS, <= 4.x.x, we had the `replay()` method. As this was a special case of multicast, behind the scenes, this code `source$.replay(null, 1)` would mean `source$.multicast(new ReplaySubject(1))`. So as we don’t have this extra `replay()` API in RxNext, I would expect the code below in the reproduce example to work.

### RxJS Version

Version 5.0.0-alpha.6

### Environment & Operating System

node version 4.1.1
npm version 2.14.4

Kernel name: Linux
Kernel release: 3.13.0-52-generic
Kernel version: 86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015
Machine hardware: x86_64
Processor: x86_64
Hardware platform: x86_64
OS: GNU/Linux

### Reproduce Error

```shell
$ npm install @reactivex/rxjs@5.0.0-alpha.6
```

```js
// script.js
var Rx = require(`@reactivex/rxjs`)

Rx.Observable.create(function (observer) {
  observer.onNext(1)
  observer.onCompleted()
}).multicast(new Rx.ReplaySubject(1)).connect()
```

```shell
$ node script.js
```

**Comment by Frikki** [comment]
So I got to look closer at the source code, and I can see that I am using the `multicast()` and `Observable` wrong. The script should probably be like below to work.

```js
// script.js
var Rx = require(`@reactivex/rxjs`)

Rx.Observable.create(function (observer) {
  observer.next(1)
  observer.complete()
}).multicast(function () { return new Rx.ReplaySubject(1) }).connect()
```

So much new.
