### ISSUE TITLE
ERR_UNSUPPORTED_DIR_IMPORT when importing rxjs/operators

### ISSUE THREAD

**Issue by blanchma** [ReactiveX/rxjs#6187]
## Bug Report

**Current Behavior**
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/blanchma/learning/rxjs-local/node_modules/rxjs/operators' is not supported resolving ES modules imported from /Users/blanchma/learning/rxjs-local/test.js
Did you mean to import rxjs-local/node_modules/rxjs/operators/index.js?
    at finalizeResolution (internal/modules/esm/resolve.js:272:17)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///Users/blanchma/learning/rxjs-local/node_modules/rxjs/operators'
}
```

**Expected behavior**
```
Import and run
```

**Reproduction**
```
git@github.com:blanchma/rxjs-import-fail.git
cd rxjs-import-fail
npm install
node test.js
```

- REPL or Repo link:
https://github.com/blanchma/rxjs-import-fail

```js
node test.js
```

**Environment**
- Runtime: v14.15.3
- RxJS version: "6.6.6"

**Comment by kwonoj** [comment]
https://github.com/ReactiveX/rxjs/issues/4416

since you specified to use esm https://github.com/blanchma/rxjs-import-fail/blob/master/package.json#L6 .
