### ISSUE TITLE
Code coverage remapping intermittently fails

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/RxJS#633]
```
$ cat ./coverage/coverage-remapped.lcov  | ./node_modules/coveralls/bin/coveralls.js
cat: ./coverage/coverage-remapped.lcov: No such file or directory
[error] "2015-10-30T17:17:58.950Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2015-10-30T17:17:58.952Z"  'input: ' ''
[error] "2015-10-30T17:17:58.953Z"  'error from convertLcovToCoveralls'
/home/travis/build/ReactiveX/RxJS/node_modules/coveralls/bin/coveralls.js:18
```

states remapped coverage is not generated somehow. It is intermittent and does not blocks PR, but problematic since coverage is not reported for certain commits.

**Comment by kwonoj** [comment]
Starting from `remap-istanbul` module, checking if it's possible to get verbose output from it. (https://github.com/SitePen/remap-istanbul/issues/13)

**Comment by kwonoj** [comment]
One additional log shows bit more detail

>node lib/stage_sourcemap.js && remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped.json && remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped.lcov -t lcovonly && remap-istanbul -i coverage/coverage.json -o coverage/coverage-remapped -t html
Error: Could not find file: "/home/travis/build/ReactiveX/RxJS/dist/cjs/util/ArgumentOutOfRangeError.js.map"
    at readJSON (/home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/lib/remap.js:133:11)
    at /home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/lib/remap.js:170:21
    at Array.forEach (native)
    at /home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/lib/remap.js:153:22
    at Array.forEach (native)
    at remap (/home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/lib/remap.js:152:12)
    at /home/travis/build/ReactiveX/RxJS/node_modules/remap-istanbul/bin/remap-istanbul:121:19
    at process._tickCallback (node.js:368:9)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)

one of source map was not available to be remapped.

**Comment by kwonoj** [comment]
Complete build log can be found at https://travis-ci.org/ReactiveX/RxJS/builds/89560829

**Comment by kwonoj** [comment]
Closed by https://github.com/ReactiveX/RxJS/pull/664
