### ISSUE TITLE
fromEvent incorrect arg order causes infinite recursion

### ISSUE THREAD

**Issue by ronag** [ReactiveX/rxjs#6474]
Doing:

```js
fromEvent('abort', signal)
```

Causes:

```js
    err: {
      "type": "RangeError",
      "message": "Maximum call stack size exceeded",
      "stack":
          RangeError: Maximum call stack size exceeded
              at isEventTarget (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:63:5)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:31:9)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:48:13)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:48:13)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:48:13)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:48:13)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:48:13)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:48:13)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:48:13)
              at setupSubscription (/usr/src/app/node_modules/rxjs/internal/observable/fromEvent.js:48:13)
    }
```

It should be

```js
fromEvent(signal, 'abort')
```

However, a bit better error handling might be appropriate here? Maybe at least check if the sourceObj is an array?

**Comment by mgred** [comment]
This is because the given `string` is identified as an [_ArrayLike_](https://github.com/ReactiveX/rxjs/blob/master/src/internal/util/isArrayLike.ts). I will create a PR to fix the funtion to not let a `string` pass.

**Comment by hgaleh** [comment]
How can we participate?
