### ISSUE TITLE
Intermittent test case failure 

### ISSUE THREAD

**Issue by kwonoj** [ReactiveX/rxjs#6630]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

One of test is failing intermittently on CI like below:

```
1) Observable
       should handle sync errors within a test scheduler:
     AssertionError: 
Expected 
	{"frame":0,"notification":{"kind":"E","error":{"name":"RangeError","message":"Maximum call stack size exceeded"}}}
	
to deep equal 

      at TestScheduler.observableMatcher [as assertDeepEqual] (dist/spec/helpers/observableMatcher.js:42:14)
          -> /home/runner/work/rxjs/rxjs/spec/helpers/observableMatcher.ts:45:10
      at /home/runner/work/rxjs/rxjs/dist/src/internal/testing/TestScheduler.js:183:23
          -> /home/runner/work/rxjs/rxjs/src/internal/testing/TestScheduler.ts:216:14
      at Array.filter (<anonymous>)
      at TestScheduler.flush (dist/src/internal/testing/TestScheduler.js:181:43)
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Reproduction**

** Please provide repro code does not involves framework, or other setups to address this bug is specific to rxjs core **

- REPL or Repo link:
(you can use https://stackblitz.com/ to create one to attach here)

```js
var your => (code) => here;
```

**Environment**
- Runtime: [e.g. Node v${x}, Chrome v${x}]
- RxJS version:
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version, config]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by kwonoj** [comment]
with PR like this https://github.com/ReactiveX/rxjs/pull/6629/checks?check_run_id=3797936477

Unfortunately no way to reliably reproduce this issue locally yet.

**Comment by kwonoj** [comment]
We skipped test for now https://github.com/ReactiveX/rxjs/pull/6603 but should investigate further.
