### ISSUE TITLE
TypeError: Scheduler.schedule is not a function

### ISSUE THREAD

**Issue by TylorS** [ReactiveX/RxJS#898]
I have some code here for Rx 4 that works just fine - http://jsbin.com/tijopu/edit?js,console

Yet the equivalent for Rx 5 throws an Error
```js
TypeError: scheduler.schedule is not a function
    at ArrayObservable._subscribe (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:892:38)
    at ArrayObservable.Observable.subscribe (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:168:29)
    at Object.subscribeToResult (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:7564:27)
    at MergeMapSubscriber._innerSub (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:4267:38)
    at MergeMapSubscriber._next (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:4259:22)
    at MergeMapSubscriber.Subscriber.next (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:725:18)
    at RangeObservable._subscribe (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:1742:28)
    at Observable._subscribe (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:196:28)
    at Observable._subscribe (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:196:28)
    at Observable.subscribe (https://npmcdn.com/@reactivex/rxjs@5.0.0-alpha.10/dist/global/Rx.js:168:29)
```

A jsbin for the RxJS 5 (alpha 10) version is here - http://jsbin.com/jetule/5/edit?js,console

**Comment by TylorS** [comment]
Also the same with the alpha 12 version - http://jsbin.com/jetule/11/edit?html,js,console

**Comment by kwonoj** [comment]
RxJS5's `concatMap` doesn't have polymorphic behavior to accept observable directly, instead have strict interface of 

```js
concatMap<T, R>(
  project: (value: T, index: number) => Observable<any>, 
  projectResult?: (outerValue: T, innerValue: any, outerIndex: number, innerIndex: number) => R)
```

modifying code to 

```
Rx.Observable.range(1, 1000)
  .concatMap((x) => Rx.Observable.fromArray(x))
  .reduce(...
```
would work. http://jsbin.com/nidiripeje/edit?html,js,console

**Comment by TylorS** [comment]
Thank you @kwonoj for the information.

**Comment by anwarhamr** [comment]
I had the problem as well but mine seemed to be with expecting the default value to be passed to the function
Results in same error:
```
      return Observable.from(x)
        .mergeMap(Observable.fromPromise);
```
FIXED:
```
      return Observable.from(x)
        .mergeMap(x=>Observable.fromPromise(x));
```
